### Get all reviews
GET http://localhost:8080/api/pokemon/1/reviews
Accept: application/json

### Get a specific review by ID
GET http://localhost:8080/api/pokemon/2/reviews/2
Accept: application/json

### Create a new review
POST http://localhost:8080/api/pokemon/1/reviews
Accept: application/json
Content-Type: application/json

{
    "title": "Great Pokemon!",
    "content": "I really enjoyed this Pokemon.",
    "rating": 5
}

### Update an existing review
PUT http://localhost:8080/api/pokemon/2/reviews/2
Content-Type: application/json

{
    "title": "Updated Review",
    "content": "Updated content for the review.",
    "rating": 4
}

### Delete a review
DELETE http://localhost:8080/api/pokemon/1/reviews/7